package project.adapter.in.web.Utils;

public enum Code {
    BETTING_ACCOUNT_NOT_FOUND,
    MOMO_ACCOUNT_NOT_FOUND,
    REDUCER_NOT_FOUND,
    MATCH_NOT_FOUND,
    BET_SLIP_NOT_FOUND,
    INVALID_AMOUNT,
    INVALID_SLIP_INDEX,
    INVALID_BONUS_INDEX,
    INVALID_MATCH_REQUEST,
    INVALID_OUTCOME_REQUEST,
    INSUFFICIENT_FUNDS,
    INTERNAL_ERROR,
    LIMIT_EXCEEDED,
    REDUCER_ALREADY_EXIST,
    MOMO_ACCOUNT_ALREADY_EXISTS,
    DTO_VALIDATION_ERROR,
    INVALID_INPUT,
    INVALID_HTTP,
    BETTING_ACCOUNT_ERROR,
    MATCH_ERROR,
    MOMO_ACCOUNT_ERROR,
    BETTING_ACCOUNT_ALREADY_EXISTS
}
